# Generated by Django 5.1.7 on 2025-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('six_month', 'Six Month'), ('yearly', 'Yearly'), ('five_year', 'Five Year'), ('ten_year', 'Ten Year')], default='monthly', max_length=20),
        ),
    ]
